---
title: "uga reach jmmi v3"
author: "Anthony Twesigye"
date: "27/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Brief overview of changes from uganda_jmmi_v2 to uga_reach_jmmi_v3

The [**uga_reach_jmmi_v3**](https://github.com/twesigye10/uga_reach_jmmi_v3) is 
based on the [**uganda_jmmi_v2**](https://github.com/twesigye10/uganda_jmmi_v2) 
with modifications in terms of code refactoring and how scripts are sourced and 
objects created.
The current version ensures that the results are consistent with those from the 
previous script.

Where possible `uga reach jmmi v3` tries to:

- Create functions in situations where a part of the code is repeated a few time 
to calculate something similar with a few differences.
- Create functions where scripts are sourced in the middle of the main script 
reading objects from the main script and creating new objects for the main script. 
This was a bit challenging to understand the workflow of the script for 
its maintenance and improvement.

### location data processing

With `v2`, location data was processed in `locations_list.R` script and the script 
was then sourced into the main script. 
With `v3`, there are two functions `settlement_district, regroup_regions` for this task.
These functions are included in the `functions.R` script.

### Code refactoring

- from v2: `line 75 - 119`, are now chained in one pipe in v3: `line 71 - 101`

- `nan_inf_to_na` function transferred to the `functions.R` script

### Calculation of mean summaries (v3: `line 140 - 158`, v2: `line 183 - 211`)
- Using the `prices_for_pct_change_summary` function for the calculation of mean 
summaries at market, settlement, district, regional and national levels

### calculation of meb

- v2 sources `meb_calc.R` script for meb calculation in the middle of the main script.
- v3 sources `meb_calc.R` script at the start of the main script and calls the 
function `meb_cal_func` in the middle of the script.

### Calculation of percentage change

- v2 sources `pct_change_function.R` script at the start of the main script and
`percent_change_calc_revised.R` in the middle of the main script.
- v3 uses only the `pct_change_function.R` script sourced at the start of 
the main script and calls the `percentage_change_calculations` function in it in 
the middle of the script.

### Top n analysis (v3: `lines 290 -377`, v2: `lines 348 - 599`)

- For the `top 3` and `top 2` analysis, the code looked similar with a few difference 
which were now used as variables in a new `top_n_analysis` function in the `functions.R`
script.
- The ranking workflow was also modified using grouping.


### Non percentage vars analysis and Percentage vars analysis (v3: `line 380 - 419`, v2: `line 602 - 709`)

- `v3` introduced two functions `non_perct_vars_analysis` and `perct_vars_analysis` to
handle the processing

### Data Merge (v3: `line 422 - 516`, v2: `line 714`)

- `v2` uses the `data_merge.R` script and sources the script towards the end of 
the main script to extract items for including the final data merge output.
- `v3` extracts the items to include in the final data merge with in the main script
but introduces a new function `jmmi_datamerge_filter_rename` to help in filtering 
and renaming of columns
